"""
Markdown -> WXR(WordPress eXtended RSS) 変換スクリプト

Front matter付きMarkdownを読み、note向けのWXRファイルを生成する。
画像パスはGitHub Pages URLに自動変換される。

Markdown形式（先頭にYAML front matter）:
    ---
    title: 「ひとりDX担当」連載スタートします
    date: 2026-04-29
    slug: intro
    ---

    本文Markdown...

使い方:
    # 単一記事を変換
    python md2wxr.py ../articles/01-intro.md

    # ../articles/ 配下を全部1つのWXRにまとめる
    python md2wxr.py --all

    # 出力先指定
    python md2wxr.py ../articles/01-intro.md -o ../wxr/intro.xml

オプション:
    -o, --output       出力WXRファイル
    -d, --output-dir   出力ディレクトリ（デフォルト: ../wxr/）
    --all              ../articles/ 配下を全部1つにまとめて出力
    --articles-dir     一括変換時の入力ディレクトリ
    --base-url         GitHub Pages のベースURL（デフォルト: 設定値）
    --status           note公開ステータス（draft/publish。デフォルト draft）
"""
import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

import frontmatter
import markdown as md_lib

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ARTICLES_DIR = ROOT / "articles"
DEFAULT_OUTPUT_DIR = ROOT / "wxr"
PAGES_BASE_URL = "https://haruhito0526-2.github.io/vibe-coding-records"
SITE_TITLE = "vibe-coding-records"

MARKDOWN_EXTENSIONS = ["fenced_code", "tables", "nl2br", "sane_lists"]

WXR_HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
    xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:wp="http://wordpress.org/export/1.2/">
<channel>
  <title>{site_title}</title>
  <link>{base_url}/</link>
  <description>Generated by md2wxr.py</description>
  <pubDate>{now_rfc822}</pubDate>
  <language>ja</language>
  <wp:wxr_version>1.2</wp:wxr_version>
  <wp:base_site_url>{base_url}/</wp:base_site_url>
  <wp:base_blog_url>{base_url}/</wp:base_blog_url>
"""

WXR_FOOTER = """</channel>
</rss>
"""

ITEM_TEMPLATE = """  <item>
    <title>{title}</title>
    <link>{permalink}</link>
    <pubDate>{pub_date_rfc822}</pubDate>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <guid isPermaLink="false">{permalink}?p={post_id}</guid>
    <description></description>
    <content:encoded><![CDATA[{content_html}]]></content:encoded>
    <excerpt:encoded><![CDATA[{excerpt}]]></excerpt:encoded>
    <wp:post_id>{post_id}</wp:post_id>
    <wp:post_date><![CDATA[{post_date_local}]]></wp:post_date>
    <wp:post_date_gmt><![CDATA[{post_date_gmt}]]></wp:post_date_gmt>
    <wp:comment_status><![CDATA[open]]></wp:comment_status>
    <wp:ping_status><![CDATA[open]]></wp:ping_status>
    <wp:post_name><![CDATA[{slug}]]></wp:post_name>
    <wp:status><![CDATA[{status}]]></wp:status>
    <wp:post_parent>0</wp:post_parent>
    <wp:menu_order>0</wp:menu_order>
    <wp:post_type><![CDATA[post]]></wp:post_type>
    <wp:post_password><![CDATA[]]></wp:post_password>
    <wp:is_sticky>0</wp:is_sticky>
  </item>
"""


def to_pages_url(local_path: str, base_url: str) -> str:
    """ローカル相対パス '../images/png/foo.png' や 'images/png/foo.png' を Pages URL に変換"""
    p = local_path.replace("\\", "/").lstrip("./").lstrip("/")
    while p.startswith("../"):
        p = p[3:]
    return f"{base_url.rstrip('/')}/{p}"


def rewrite_image_paths(html: str, base_url: str) -> str:
    """Markdown→HTML 後の <img src="..."> をGitHub Pages URLに置換"""
    def repl(match: re.Match) -> str:
        src = match.group(1)
        if src.startswith(("http://", "https://", "data:")):
            return match.group(0)
        new_src = to_pages_url(src, base_url)
        return f'src="{new_src}"'
    return re.sub(r'src="([^"]+)"', repl, html)


def render_html(md_text: str, base_url: str) -> str:
    html = md_lib.markdown(md_text, extensions=MARKDOWN_EXTENSIONS)
    return rewrite_image_paths(html, base_url)


def to_rfc822(dt: datetime) -> str:
    """Tue, 29 Apr 2026 00:00:00 +0000"""
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S +0000")


def parse_date(value, fallback_path: Path) -> datetime:
    if value is None:
        ts = fallback_path.stat().st_mtime
        return datetime.fromtimestamp(ts, tz=timezone.utc)
    if isinstance(value, datetime):
        return value if value.tzinfo else value.replace(tzinfo=timezone.utc)
    s = str(value)
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d", "%Y/%m/%d"):
        try:
            return datetime.strptime(s, fmt).replace(tzinfo=timezone.utc)
        except ValueError:
            continue
    raise ValueError(f"日付の形式を解釈できません: {value}")


def make_excerpt(text: str, n: int = 120) -> str:
    plain = re.sub(r"!\[[^\]]*\]\([^)]+\)", "", text)
    plain = re.sub(r"\[[^\]]*\]\([^)]+\)", "", plain)
    plain = re.sub(r"[#>*`_~\-]", "", plain)
    plain = re.sub(r"\s+", " ", plain).strip()
    return plain[:n]


def build_item(md_path: Path, post_id: int, base_url: str, status: str) -> str:
    post = frontmatter.load(md_path)
    meta = post.metadata or {}
    title = meta.get("title") or md_path.stem
    slug = meta.get("slug") or md_path.stem
    dt = parse_date(meta.get("date"), md_path)
    permalink = f"{base_url.rstrip('/')}/articles/{slug}.html"

    content_html = render_html(post.content, base_url)
    excerpt = meta.get("excerpt") or make_excerpt(post.content)

    return ITEM_TEMPLATE.format(
        title=escape(str(title)),
        permalink=escape(permalink),
        pub_date_rfc822=to_rfc822(dt),
        post_id=post_id,
        content_html=content_html,
        excerpt=escape(excerpt),
        post_date_local=dt.strftime("%Y-%m-%d %H:%M:%S"),
        post_date_gmt=dt.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"),
        slug=escape(str(slug)),
        status=escape(status),
    )


def collect_targets(args) -> list[Path]:
    if args.all:
        articles_dir = Path(args.articles_dir).resolve()
        return sorted(articles_dir.glob("*.md"))
    if args.input:
        return [Path(args.input).resolve()]
    return []


def run(args):
    targets = collect_targets(args)
    if not targets:
        print("Markdownファイルか --all を指定してください", file=sys.stderr)
        sys.exit(2)
    for p in targets:
        if not p.exists():
            print(f"file not found: {p}", file=sys.stderr)
            sys.exit(1)

    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    if args.output:
        out_path = Path(args.output).resolve()
    elif args.all:
        out_path = output_dir / f"all-{datetime.now().strftime('%Y%m%d-%H%M%S')}.xml"
    else:
        out_path = output_dir / (targets[0].stem + ".xml")

    base_url = args.base_url.rstrip("/")
    items_xml = []
    for i, md_path in enumerate(targets, start=1):
        print(f"  -> {md_path.name}")
        items_xml.append(build_item(md_path, post_id=i, base_url=base_url, status=args.status))

    header = WXR_HEADER.format(
        site_title=SITE_TITLE,
        base_url=base_url,
        now_rfc822=to_rfc822(datetime.now(timezone.utc)),
    )
    out_path.write_text(header + "".join(items_xml) + WXR_FOOTER, encoding="utf-8")
    print(f"[md2wxr] saved: {out_path}  ({len(targets)} item(s))")


def main():
    parser = argparse.ArgumentParser(description="Markdown -> WXR (note インポート用) 変換")
    parser.add_argument("input", nargs="?", help="入力Markdownファイル")
    parser.add_argument("-o", "--output", help="出力WXRファイル")
    parser.add_argument("-d", "--output-dir", default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument("--all", action="store_true", help=f"{DEFAULT_ARTICLES_DIR} 配下を全部")
    parser.add_argument("--articles-dir", default=str(DEFAULT_ARTICLES_DIR))
    parser.add_argument("--base-url", default=PAGES_BASE_URL)
    parser.add_argument("--status", default="draft", choices=["draft", "publish"])
    args = parser.parse_args()
    run(args)


if __name__ == "__main__":
    main()
